### ISSUE TITLE
When I compile with `MMU2` I get an error: 'mmu2_M600' was not declared in this scope

### ISSUE THREAD

**Issue by Legired** [revilor/Marlin#4]
Hello,

I try to make MMU2 work with my prusa based on Ramps 1.4 board, but when i want compile marlin, i got this error 
![capture](https://user-images.githubusercontent.com/33747013/51183236-eb369d80-18d0-11e9-9ea0-e9313957cb5c.PNG)

I put my Configuration and Configuration_adv below

Thx in advance 

Configuration.h : https://pastebin.com/DhqsBkD9

Configuration_adv.h : https://pastebin.com/9EAjSVR3

**Comment by dcwalmsley** [comment]
Fix line 986 of the Configuration.h.  You do not have it enabled.  I believe this will fix your compile issue.

**Comment by Legired** [comment]
same problem with this modification :/

**Comment by dcwalmsley** [comment]
Recommend you look at my config file in "Request validation of my Configuration" post and look over what I setup with respect to filament loading/unloading and make any change you feel will help your compiling issue.

Also recommend you download latest files from Revilor's SRC folder/files and see if it will compile successfully.

**Comment by Legired** [comment]
same problem with your configuration files ... 

i download again the src folder and same problem :(

**Comment by revilor** [comment]
M600 requires LCD menus.
So you either have to enable PRUSA_MMU2_MENUS or

disable ADVANCED_PAUSE_FEATURE and change PRUSA_MMU2_FILAMENT_RUNOUT_SCRIPT to not use M600

I'll add a sanity check to check for this.

**Comment by Legired** [comment]
i don't have lcd on my printer, i use octopi :/

**Comment by revilor** [comment]
So disable ADVANCED_PAUSE_FEATURE and use

#define PRUSA_MMU2_FILAMENT_RUNOUT_SCRIPT ""

to disable the runout check or define whatever gcodes you would like execute on filament runout.

**Comment by Legired** [comment]
Thx, i put M25, everything looking good for the moment !

**Comment by Legired** [comment]
Hello, 

I do some test during the day, and i got a problem during printing, sometime the print stop and i can see "RX Buffer overrun" in the log, do you have any idea where this come from ? 

I use a Ramps 1.4

**Comment by revilor** [comment]
I tried to reduce the buffers to the bare minimum, looks like for some specific situations I went a step too far. Please change

Marlin/src/HAL/HAL_AVR/MarlinSerial.h line 283 to

static constexpr unsigned int RX_SIZE   = 64;

This should help.

**Comment by revilor** [comment]
Sorry, Serial.h is the wrong buffer. I guess you have the revision of mmu2.h with 

line 91: char rx_buffer[8];

This is too small, please change to

char rx_buffer[16];

**Comment by Legired** [comment]
i got the version with char" rx_buffer[16];" already , i put 32 ?

**Comment by revilor** [comment]
If 16 is too small please try 32. 

If you have PRUSA_MMU2_DEBUG enabled, it would be great if you could post the serial output before the rx buffer overrun occurs. There might be a bug in handling the buffer because 16 should be sufficent from my point of view.

**Comment by Legired** [comment]
I got PRUSA_MMU_DEBUG but, i don't have more than "XR BUFFER OVERRUN" in the log :/, i try with 32 and i tell you if it's good or not tomorrow

**Comment by Legired** [comment]
Still have th RX Buffer overrun after flashing with 32

**Comment by revilor** [comment]
Now that's weird as a buffer of 16 should be more than enough. The MMU debug output would be helpful or some gcode to reproduce this behaviour.

**Comment by Legired** [comment]
![capture](https://user-images.githubusercontent.com/33747013/51429842-6b336f00-1c13-11e9-93cf-4d90a794f3b5.PNG)

No light on the mmu2, it's append randomly, i don't know why .... because, when it's happen during the print, i only use one filament, the mmu2 was in idle

**Comment by revilor** [comment]
Should be fixed with the latest commit on my branch. "rx buffer overrun" can still happen but should no longer freeze the print.

Looks like there is no MMU present because the buffer overrun happens when the printer is waiting for the "start" string from the MMU. So if you did not deactivate the MMU on purpose there might be a hardware/wiring issue.

**Comment by Legired** [comment]
I can't see your branch with "rx buffer overrun'

**Comment by revilor** [comment]
Latest commit on the MMU2 branch.

**Comment by dcwalmsley** [comment]
Unless there is any objections, I plan to close this in the next 24 hrs.
